# name: phone
type: MobilePage
route_urls:
  /: blsm_controller.html
  /broadcast: blsm_broadcast.html
  /player: blsm_player.html
event_kwargs:
  # record:
  #   namespace: /phone
  device_motion:
    # namespace: /
    # namespace: /blsm_phone
  